# Generated by Django 6.0 on 2025-12-14 12:20

import django.core.validators
import django.db.models.deletion
import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=1500)),
                ('release_year', models.PositiveIntegerField()),
                ('poster_image', models.ImageField(upload_to=movies.models.poster_image_upload_path)),
                ('age_restriction', models.PositiveIntegerField(default=0, help_text='Age restriction in years (0 means suitable for all ages).', validators=[django.core.validators.MaxValueValidator(21)])),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movies.director')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
                ('original_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_movies', to='core.language')),
            ],
        ),
    ]
