# Generated by Django 6.0 on 2025-12-14 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(default=120, help_text='Duration of movie in minutes', validators=[django.core.validators.MinValueValidator(1, message='Duration must be at least 1 minute.'), django.core.validators.MaxValueValidator(500, message='Duration cannot exceed 500 minutes.')]),
            preserve_default=False,
        ),
    ]
