# Generated by Django 6.0 on 2025-12-14 15:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('movies', '0003_movie_duration'),
        ('theaters', '0001_squashed_0002_alter_theaterhall_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowingFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dubbing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.language')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showing_variants', to='showings.showingformat')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showing_variants', to='movies.movie')),
                ('subtitles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.language')),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('ticket_price', models.DecimalField(decimal_places=2, help_text='Price in EUR', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0, message='Price must be a non-negative value.')])),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showings', to='theaters.theaterhall')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showings', to='showings.showingvariant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='showingvariant',
            constraint=models.UniqueConstraint(fields=('movie', 'format', 'subtitles', 'dubbing'), name='unique_showing_variant', nulls_distinct=False, violation_error_code='unique_showing_variant_violation', violation_error_message='A showing variant with this combination of movie, format, subtitles, and dubbing already exists.'),
        ),
        migrations.AddConstraint(
            model_name='showingvariant',
            constraint=models.CheckConstraint(condition=models.Q(('dubbing__isnull', False), ('subtitles__isnull', False), _negated=True), name='no_dubbing_and_subtitles_simultaneously', violation_error_code='no_dubbing_and_subtitles_simultaneously_violation', violation_error_message='A movie variant cannot have both dubbing and subtitles simultaneously.'),
        ),
    ]
