# Generated by Django 6.0 on 2025-12-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showing',
            old_name='hall',
            new_name='theater_hall',
        ),
    ]
