# Generated by Django 6.0 on 2025-12-14 14:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('theaters', '0001_initial'), ('theaters', '0002_alter_theaterhall_number')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="Name of the theater hall (e.g., 'Hall 1', 'Hall 2').", max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Theater hall number must contain only letters, numbers, and spaces.', regex='^[A-Za-z0-9 ]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(help_text='Row number of the seat (starting from 1).', validators=[django.core.validators.MinValueValidator(1)])),
                ('number', models.PositiveIntegerField(help_text='Seat number within the row (starting from 1).', validators=[django.core.validators.MinValueValidator(1)])),
                ('theater_hall', models.ForeignKey(help_text='The theater hall to which this seat belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theaters.theaterhall')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('theater_hall', 'row', 'number'), name='unique_seat_per_hall', violation_error_code='unique_seat_per_hall_violation', violation_error_message='A seat with this row and number already exists in the specified theater hall.')],
            },
        ),
    ]
