# Generated by Django 6.0 on 2025-12-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text="ISO 639-1 language code (e.g., 'EN' for English)", max_length=10, unique=True)),
            ],
        ),
    ]
